### ISSUE TITLE
loading polyfill's

### ISSUE THREAD

**Issue by druppy** [svi3c/jasmine-ts#1]
Hi ...

I have been using jasmine-ts for a while and it looks nice, but I am not sure how to load polyfills like node-fetch.

It seems like a good idea to include the polyfill as a helpers and enable "allowJS" in tsconfig, but it still does not load the "fetch" function in the global scope as expected.

Is this an expected behavior, or is it some kind of bug ?

/BL

**Comment by svi3c** [comment]
Hi @druppy,

when I understand you correctly, you expect node-fetch to place the `fetch()` function on the global scope.
This should not be the case (It's not actually a polyfill, but a commonjs module). In the [docs](https://www.npmjs.com/package/node-fetch) fetch is directly imported.

I got it work the following way:
* Install the typings via `typings i -SG dt~node-fetch`
* Set the `target` of your ts-compiler to `"es2015"` or alternatively install typings and polyfills for [es6-promise](https://www.npmjs.com/package/es6-promise). You need this, because node-fetch uses the es6 promise API.
* directly import node-fetch where you are using it: `import * as fetch from "node-fetch";`

**Comment by druppy** [comment]
Thanks, for keeping me on track, i was missing the typings for node-fetch. 

It now works with target "es5" and es6-promise, not it is time for more serious testings, written in pure typescript ... how cool is that :-)

**Comment by svi3c** [comment]
Glad I could help! 
Good luck! :)
