### ISSUE TITLE
Question: which reporter to use for jasmine-ts to file?

### ISSUE THREAD

**Issue by tomer-ben-david** [svi3c/jasmine-ts#23]
So that I can see the report in Jenkins for example.

This is what I currently have, no report files produced, what should I use to produce report files (preferably readable by Jenkins..)

```
  "reporters": [
    {
      "name": "jasmine-spec-reporter#SpecReporter",  
      "options": {
        "displayStacktrace": "all"
      }
    }
  ]
```

Thanks.

**Comment by Pineapples** [comment]
It depends on what reporter you would like to use, I use a JUnit reporter from the package [jasmine-reporters](https://github.com/larrymyers/jasmine-reporters).

To use the reporter you need to use a helper file and then initialize the reporter in the helper file:

```
const JUnitReporter = require('jasmine-reporters').JUnitXmlReporter;

jasmine.getEnv().addReporter(new JUnitReporter({
    savePath: '.jasmine'
}));
```

**Comment by ert78gb** [comment]
Version 0.3.2 support the `--reporter` command line parameter. I think the question also answered, but feel free to reopen the issue and describe what is missing.

**Comment by nagyzsolthun** [comment]
How to use the `--reporter` command line parameter? E.g. `jasmine-ts --reporter jasmine-reporters#JUnitXmlReporter` fails with "No specs found"

**Comment by ert78gb** [comment]
As described in the jasmine [documentation](https://jasmine.github.io/setup/nodejs.html#--reporter). :)

Prior to 0.3.2 `jasmine-ts` the jasmine config file were parsed and the reporters were set based on that. Jasmine has a built-in command line argument that can handle reporters. So I removed this feature because it had increased the complexity of this lib. Because the changes of the reporter initialisation and the config file structure should be tracked.

The jasmine documentation is not perfect, it does not mention how to provide the `--reporter` argument. 
The reporter argument should be a node module which is a `default export class` it will be instantiated. 
The relevant [code](https://github.com/jasmine/jasmine-npm/blob/8dd16c21005d16c8de73e6c03180adc9bc297f0d/lib/loadConfig.js#L23)
As you see from the referenced code the reporter will be loaded by `require(env.reporter)` so the value of the argument should be 
- relative path to the `loadConfig.js` file.
- absolute path
- node module
The first option is not a real option.

The common practice is you define a helper file
```javascript
const { SpecReporter } = require('jasmine-spec-reporter')

jasmine.getEnv().clearReporters()
jasmine.getEnv().addReporter(new SpecReporter({
      prefixes: {
        failed: ':( ',
        pending: '? ',
        successful: ':) '
      }
    }
))
``` 

Finally, I try to answer to your question:
- create a reporter file, default export the class 
- set `--reporter` with absolute file path

```javascript
// custom-reporter.js
const { SpecReporter } = require('jasmine-spec-reporter')

class CustomReporter extends SpecReporter {
  constructor() {
    super({
      prefixes: {
        failed: ':( ',
        pending: '? ',
        successful: ':) '
      }
    });
  }
}

module.exports = CustomReporter
```

I think the `--reporter` argument is useful when your IDE use a custom reporter to visualise the test results like IntelliJ does.

There are 2 open PR (jasmine/jasmine-npm#77 , jasmine/jasmine-npm#159) in the `jasmine-npm` repo that try to add the deleted feature to the core lib.
